project:
  type: book

book:
  title: "acs_cancer"
  author: "Norah Jones"
  date: "10/9/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

